import Gc.Reachability.Reachable.Lemmas.Common
import Gc.Reachability.Reachable.Lemmas.Enter
import Gc.Reachability.Reachable.Lemmas.Exit
import Gc.Reachability.Reachable.Lemmas.MakeObjStack
import Gc.Reachability.Reachable.Lemmas.MakeObjRegion
import Gc.Reachability.Reachable.Lemmas.MakeRegion
import Gc.Reachability.Reachable.Lemmas.VarAsgn
import Gc.Reachability.Reachable.Lemmas.FieldAsgn
import Gc.Reachability.Reachable.Lemmas.Merge
import Gc.Reachability.Reachable.Lemmas.Swap
