import Gc.Reachability.Referencable.Lemmas.Common
import Gc.Reachability.Referencable.Lemmas.Enter
import Gc.Reachability.Referencable.Lemmas.Exit
import Gc.Reachability.Referencable.Lemmas.FieldAsgn
import Gc.Reachability.Referencable.Lemmas.MakeObjRegion
import Gc.Reachability.Referencable.Lemmas.MakeObjStack
import Gc.Reachability.Referencable.Lemmas.MakeRegion
import Gc.Reachability.Referencable.Lemmas.Merge
import Gc.Reachability.Referencable.Lemmas.Swap
import Gc.Reachability.Referencable.Lemmas.VarAsgn
